INSERT INTO artists (name, bio) VALUES
    ('Serj Tankian', 'Vocalista, compositor e ativista armênio-americano, conhecido como líder da banda System of a Down e por sua carreira solo experimental'),
    ('Mike Shinoda', 'Rapper, produtor, multi-instrumentista e um dos fundadores do Linkin Park, com carreira solo focada em hip hop e música eletrônica'),
    ('Michel Teló', 'Cantor, compositor e músico brasileiro de música sertaneja, conhecido por sucessos de alcance internacional'),
    ('Guns N'' Roses', 'Banda norte-americana de hard rock formada em Los Angeles, conhecida por misturar rock pesado com influências de blues e punk'),
    ('Chappell Roan', 'Cantora e compositora pop norte-americana, conhecida por estética teatral, letras confessionais e forte influência do synth-pop'),
    ('Ney Matogrosso', 'Cantor e performer brasileiro, ícone da MPB, conhecido por sua voz aguda, presença de palco marcante e carreira inovadora'),
    ('Rauw Alejandro', 'Cantor e compositor porto-riquenho, destaque do reggaeton e do pop latino contemporâneo'),
    ('Rosalía', 'Cantora, compositora e produtora espanhola que combina flamenco com pop, música eletrônica e influências urbanas'),
    ('Sufjan Stevens', 'Cantor, compositor e multi-instrumentista norte-americano, referência no folk indie e na música experimental'),
    ('Clarice Falcão', 'Cantora, compositora, atriz e roteirista brasileira, conhecida por letras irônicas e estilo pop alternativo'),
    ('Almir Sater', 'Cantor, compositor e violeiro brasileiro, referência da música regional e da viola caipira'),
    ('Shakira', 'Cantora, compositora e dançarina colombiana, conhecida por misturar pop, música latina e influências árabes'),
    ('Tim Bernardes', 'Cantor, compositor e produtor brasileiro, integrante da banda O Terno e destaque da música alternativa nacional'),
    ('Gal Costa', 'Cantora brasileira, uma das maiores vozes da MPB e figura central do movimento tropicalista'),
    ('Guitarricadelafuente', 'Cantor e compositor espanhol que mistura folk, flamenco e pop com forte identidade estética'),
    ('The Beatles', 'Banda britânica de rock formada em Liverpool, considerada uma das mais influentes da história da música'),
    ('Fiona Apple', 'Cantora e compositora norte-americana conhecida por letras introspectivas, arranjos complexos e estilo artístico singular')

ON CONFLICT DO NOTHING;


INSERT INTO albums (title, release_year) VALUES
    ('Harakiri', 2012),
    ('Post Traumatic', 2018),
    ('Bem Sertanejo', 2014),
    ('Na Balada', 2011),
    ('Appetite for Destruction', 1987),
    ('Use Your Illusion I', 1991),
    ('Use Your Illusion II', 1991),
     ('Greatest hits', 2004),
    ('The Rise and Fall of a Midwest Princess', 2023),
    ('Bandido', 1976),
    ('Pecado', 1977),
    ('Ney Mato Grosso', 1981),
    ('Olhos de Farol', 1999),
    ('RR', 2023),
    ('Motomami', 2022),
    ('Lux', 2026),
    ('Illinois', 2005),
    ('Carrie & Lowell', 2015),
    ('Monomania', 2013),
    ('Problema Meu', 2016),
    ('Doma', 1982),
    ('Estradeiro', 1981),
    ('Dónde Están los Ladrones?', 1998),
    ('Piez descalzos', 1995),
    ('Mil Coisas Invisíveis', 2022),
    ('Gal Tropical', 1979),
    ('Spanish Leather', 2022),
    ('Revolver', 1966),
    ('Abbey Road', 1969),
    ('Fetch the Bolt Cutters', 2020);


INSERT INTO artist_album (artist_id, album_id) Values
    (1, 1),
    (2, 2),
    (3, 3),
    (3, 4),
    (4, 5),
    (4, 6),
    (4, 7),
    (4, 8),
    (5, 9),
    (6, 10),
    (6, 11),
    (6, 12),
    (6, 13),
    (7, 14),
    (8, 14),
    (8, 15),
    (8, 16),
    (9, 17),
    (9, 18),
    (10, 19),
    (10, 20),
    (11, 21),
    (11, 22),
    (12, 23),
    (12, 24),
    (13, 25),
    (14, 26),
    (15, 27),
    (16, 28),
    (16, 29),
    (17, 30);

